// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: articles.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (id, title, content, created_at, updated_at)
VALUES
(
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    NOW()
)

RETURNING id, title, content, created_at, updated_at
`

type CreateArticleParams struct {
	Title   string
	Content string
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle, arg.Title, arg.Content)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteArticle, id)
	return err
}

const getArticles = `-- name: GetArticles :many
SELECT id, title, content, created_at, updated_at FROM articles WHERE title ILIKE $1
`

func (q *Queries) GetArticles(ctx context.Context, title string) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, getArticles, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtidleByID = `-- name: GetArtidleByID :one
SELECT id, title, content, created_at, updated_at FROM articles WHERE id = $1
`

func (q *Queries) GetArtidleByID(ctx context.Context, id uuid.UUID) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArtidleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles SET
title= $1,
content=$2,
updated_at = NOW()
WHERE id = $3
RETURNING id, title, content, created_at, updated_at
`

type UpdateArticleParams struct {
	Title   string
	Content string
	ID      uuid.UUID
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, updateArticle, arg.Title, arg.Content, arg.ID)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
