// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: articles.sql

package database

import (
	"context"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (id, title, content, created_at, updated_at)
VALUES
(
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    NOW()
)

RETURNING id, title, content, created_at, updated_at
`

type CreateArticleParams struct {
	Title   string
	Content string
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle, arg.Title, arg.Content)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
