basePath: /v1/api
definitions:
  handlers.article:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  handlers.createArticleRequestBody:
    properties:
      content:
        type: string
      title:
        type: string
    type: object
  handlers.createArticleResponseBody:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  handlers.responseError:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: A RESTful API for a blogging platform
  title: Blogging Platform API
  version: "1.0"
paths:
  /articles/:
    get:
      consumes:
      - application/json
      description: Fetches all blog articles or blog articles specified in the quer
        field
      parameters:
      - description: optional search parameter
        in: query
        name: query
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: All articles
          schema:
            items:
              $ref: '#/definitions/handlers.article'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.responseError'
      summary: Gets all articles
      tags:
      - Articles
    post:
      consumes:
      - application/json
      description: Create a new article with the provided title and content
      parameters:
      - description: Article data
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/handlers.createArticleRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Article created
          schema:
            $ref: '#/definitions/handlers.createArticleResponseBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.responseError'
      summary: Create a new article
      tags:
      - Articles
swagger: "2.0"
