name: cd

on:
  push:
    branches: [main]

permissions: write-all
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Build server
        run: scripts/build.sh

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

      
      - name: 'Build Blog api Image'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          docker build . --tag ghcr.io/phoenixtech2003/blogapi:latest
          docker push ghcr.io/phoenixtech2003/blogapi:latest
      
      - name: Deploy to Render
        run: |
          curl "$deploy_url"
          
