name: cd

on:
  push:
    branches: [main]

permissions: write-all
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env: 
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Build server
        run: scripts/build.sh

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

      
      - name: 'Build Blog api Image' 
        run: |
          docker build . --tag ghcr.io/phoenixtech2003/blogapi:latest
          docker push ghcr.io/phoenixtech2003/blogapi:latest


      - name: Apply migrations
        run: | 
          cd sql/schema
          goose postgres $DATABASE_URL up

      
      - name: Deploy to Render
        run: |
          curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          
